package com.dam.framework.engine;

import com.dam.framework.annotation.Column;
import com.dam.framework.annotation.GeneratedValue;
import com.dam.framework.annotation.Id;

import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;

/**
 * Holds metadata about an entity class.
 * This includes table name, columns, primary key, relationships, etc.
 * 
 * @author Dev 2
 */
public class EntityMetadata {
    
    private Class<?> entityClass;
    private String tableName;
    private Field idField;
    private List<Field> fields;
    private List<RelationshipMetadata> relationships;
    private boolean idAutoGenerated;
    
    public EntityMetadata(Class<?> entityClass) {
        this.entityClass = entityClass;
        this.fields = new ArrayList<>();
        this.relationships = new ArrayList<>();
        this.idAutoGenerated = false;
    }
    
    public Class<?> getEntityClass() {
        return entityClass;
    }
    
    public String getTableName() {
        return tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    
    public Field getIdField() {
        return idField;
    }
    
    public void setIdField(Field idField) {
        this.idField = idField;
        // Check if ID is auto-generated
        if (idField != null && idField.isAnnotationPresent(GeneratedValue.class)) {
            this.idAutoGenerated = true;
        }
    }
    
    public List<Field> getFields() {
        return fields;
    }
    
    public void setFields(List<Field> fields) {
        this.fields = fields;
    }
    
    /**
     * Get relationship metadata list.
     */
    public List<RelationshipMetadata> getRelationships() {
        return relationships;
    }
    
    /**
     * Set relationship metadata list.
     */
    public void setRelationships(List<RelationshipMetadata> relationships) {
        this.relationships = relationships;
    }
    
    /**
     * Add a relationship to the metadata.
     */
    public void addRelationship(RelationshipMetadata relationship) {
        this.relationships.add(relationship);
    }
    
    /**
     * Check if the entity has any relationships.
     */
    public boolean hasRelationships() {
        return relationships != null && !relationships.isEmpty();
    }
    
    /**

     * Check if the ID field is auto-generated.
     */
    public boolean isIdAutoGenerated() {
        return idAutoGenerated;
    }
    
    /**
     * Get non-ID fields (for INSERT without auto-generated ID).
     */
    public List<Field> getNonIdFields() {
        List<Field> nonIdFields = new ArrayList<>();
        for (Field field : fields) {
            if (!field.equals(idField) || !idAutoGenerated) {
                if (!field.equals(idField)) {
                    nonIdFields.add(field);
                }
            }
        }
        return nonIdFields;
    }
    
    /**
     * Get column name for a field.
     * If @Column annotation is present, use that name, otherwise use field name.
     * 
     * @param field The field
     * @return Column name
     */
    public String getColumnName(Field field) {
        if (field.isAnnotationPresent(Column.class)) {
            Column column = field.getAnnotation(Column.class);
            if (column.name() != null && !column.name().isEmpty()) {
                return column.name();
            }
        }
        return field.getName();
    }
    
    /**
     * Get the column name of the ID field.
     */
    public String getIdColumnName() {
        if (idField == null) return "id";
        return getColumnName(idField);
    }
    
    /**
     * Get all column names.
     */
    public List<String> getAllColumnNames() {
        List<String> columnNames = new ArrayList<>();
        for (Field field : fields) {
            columnNames.add(getColumnName(field));
        }
        return columnNames;
    }
    
    /**
     * Get value from entity for a specific field.
     */
    public Object getFieldValue(Object entity, Field field) {
        try {
            field.setAccessible(true);
            return field.get(entity);
        } catch (IllegalAccessException e) {
            throw new RuntimeException("Cannot access field: " + field.getName(), e);
        }
    }
    
    /**
     * Set value to entity for a specific field.
     */
    public void setFieldValue(Object entity, Field field, Object value) {
        try {
            field.setAccessible(true);
            field.set(entity, value);
        } catch (IllegalAccessException e) {
            throw new RuntimeException("Cannot set field: " + field.getName(), e);
        }
    }
    
    /**
     * Get the ID value from an entity.
     */
    public Object getIdValue(Object entity) {
        if (idField == null) return null;
        return getFieldValue(entity, idField);
    }
    
    /**
     * Set the ID value to an entity.
     */
    public void setIdValue(Object entity, Object id) {
        if (idField != null) {
            setFieldValue(entity, idField, id);
        }
    }
}
