package com.dam.framework.engine;

import com.dam.framework.annotation.Column;
import java.lang.reflect.Field;
import java.util.List;
import java.util.StringJoiner;

/**
 * Generates SQL statements from entity metadata.
 * 
 * @author Dev 2
 */
public class SQLGenerator {
    
    /**
     * Generate INSERT SQL statement.
     * Example: INSERT INTO users (username, email, age) VALUES (?, ?, ?)
     * 
     * @param metadata Entity metadata
     * @return SQL INSERT statement
     */
    public static String generateInsertSQL(EntityMetadata metadata) {
        StringBuilder sql = new StringBuilder("INSERT INTO ");
        sql.append(metadata.getTableName()).append(" (");
        
        StringJoiner columns = new StringJoiner(", ");
        StringJoiner values = new StringJoiner(", ");
        
        List<Field> fieldsToInsert = metadata.isIdAutoGenerated() 
            ? metadata.getNonIdFields() 
            : metadata.getFields();
        
        for (Field field : fieldsToInsert) {
            columns.add(metadata.getColumnName(field));
            values.add("?");
        }
        
        sql.append(columns).append(") VALUES (").append(values).append(")");
        return sql.toString();
    }
    
    /**
     * Generate UPDATE SQL statement.
     * Example: UPDATE users SET username=?, email=?, age=? WHERE id=?
     * 
     * @param metadata Entity metadata
     * @return SQL UPDATE statement
     */
    public static String generateUpdateSQL(EntityMetadata metadata) {
        StringBuilder sql = new StringBuilder("UPDATE ");
        sql.append(metadata.getTableName()).append(" SET ");
        
        StringJoiner setClause = new StringJoiner(", ");
        
        for (Field field : metadata.getNonIdFields()) {
            setClause.add(metadata.getColumnName(field) + " = ?");
        }
        
        sql.append(setClause);
        sql.append(" WHERE ").append(metadata.getIdColumnName()).append(" = ?");
        
        return sql.toString();
    }
    
    /**
     * Generate DELETE SQL statement.
     * Example: DELETE FROM users WHERE id=?
     * 
     * @param metadata Entity metadata
     * @return SQL DELETE statement
     */
    public static String generateDeleteSQL(EntityMetadata metadata) {
        return "DELETE FROM " + metadata.getTableName() + 
               " WHERE " + metadata.getIdColumnName() + " = ?";
    }
    
    /**
     * Generate SELECT ALL SQL statement.
     * Example: SELECT id, username, email, age FROM users
     * 
     * @param metadata Entity metadata
     * @return SQL SELECT statement
     */
    public static String generateSelectSQL(EntityMetadata metadata) {
        StringBuilder sql = new StringBuilder("SELECT ");
        
        StringJoiner columns = new StringJoiner(", ");
        for (Field field : metadata.getFields()) {
            columns.add(metadata.getColumnName(field));
        }
        
        sql.append(columns);
        sql.append(" FROM ").append(metadata.getTableName());
        
        return sql.toString();
    }
    
    /**
     * Generate SELECT by ID SQL statement.
     * Example: SELECT id, username, email, age FROM users WHERE id=?
     * 
     * @param metadata Entity metadata
     * @return SQL SELECT statement with WHERE clause
     */
    public static String generateSelectByIdSQL(EntityMetadata metadata) {
        return generateSelectSQL(metadata) + 
               " WHERE " + metadata.getIdColumnName() + " = ?";
    }
    
    /**
     * Generate COUNT SQL statement.
     * Example: SELECT COUNT(*) FROM users
     */
    public static String generateCountSQL(EntityMetadata metadata) {
        return "SELECT COUNT(*) FROM " + metadata.getTableName();
    }
    
    /**
     * Generate SELECT with WHERE clause.
     * Example: SELECT id, username FROM users WHERE age > ?
     */
    public static String generateSelectWithWhereSQL(EntityMetadata metadata, String whereClause) {
        return generateSelectSQL(metadata) + " WHERE " + whereClause;
    }
}
