package com.dam.framework.core;

import com.dam.framework.dialect.Dialect;
import com.dam.framework.engine.EntityMetadata;
import com.dam.framework.engine.MetadataParser;
import com.dam.framework.engine.ResultSetMapper;
import com.dam.framework.engine.SQLGenerator;
import com.dam.framework.query.QueryBuilder;
import com.dam.framework.spi.InterceptorRegistry;

import java.lang.reflect.Field;
import java.sql.*;
import java.util.List;

/**
 * Implementation of Session interface.
 * Handles all database operations (CRUD) through JDBC.
 * 
 * Design Pattern: Part of Factory Pattern (created by SessionFactory)
 * 
 * @author Dev 1
 */
public class SessionImpl implements Session {
    
    private Connection connection;
    private Dialect dialect;
    private TransactionImpl currentTransaction;
    private boolean closed;
    
    /**
     * Create a new session with the given connection and dialect.
     * 
     * @param connection The JDBC connection
     * @param dialect The database dialect
     */
    public SessionImpl(Connection connection, Dialect dialect) {
        this.connection = connection;
        this.dialect = dialect;
        this.closed = false;
    }
    
    @Override
    public <T> T save(T entity) {
        checkClosed();
        
        // Fire pre-save interceptors
        if (!InterceptorRegistry.getInstance().firePreSave(entity)) {
            return entity; // Operation cancelled by interceptor
        }
        
        EntityMetadata metadata = MetadataParser.parse(entity.getClass());
        String sql = SQLGenerator.generateInsertSQL(metadata);
        
        try (PreparedStatement stmt = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            // Bind parameters
            List<Field> fieldsToInsert = metadata.isIdAutoGenerated() 
                ? metadata.getNonIdFields() 
                : metadata.getFields();
            
            int paramIndex = 1;
            for (Field field : fieldsToInsert) {
                Object value = metadata.getFieldValue(entity, field);
                stmt.setObject(paramIndex++, value);
            }
            
            // Execute INSERT
            int rowsAffected = stmt.executeUpdate();
            
            if (rowsAffected > 0 && metadata.isIdAutoGenerated()) {
                // Get generated key
                try (ResultSet generatedKeys = stmt.getGeneratedKeys()) {
                    if (generatedKeys.next()) {
                        Object generatedId = generatedKeys.getObject(1);
                        // Convert to appropriate type
                        generatedId = convertIdType(generatedId, metadata.getIdField().getType());
                        metadata.setIdValue(entity, generatedId);
                    }
                }
            }
            
            // Fire post-save interceptors
            InterceptorRegistry.getInstance().firePostSave(entity);
            
            return entity;
            
        } catch (SQLException e) {
            throw new RuntimeException("Failed to save entity: " + entity.getClass().getName(), e);
        }
    }
    
    @Override
    public <T> T update(T entity) {
        checkClosed();
        
        // Fire pre-update interceptors
        if (!InterceptorRegistry.getInstance().firePreUpdate(entity)) {
            return entity; // Operation cancelled by interceptor
        }
        
        EntityMetadata metadata = MetadataParser.parse(entity.getClass());
        String sql = SQLGenerator.generateUpdateSQL(metadata);
        
        try (PreparedStatement stmt = connection.prepareStatement(sql)) {
            // Bind non-ID field values
            int paramIndex = 1;
            for (Field field : metadata.getNonIdFields()) {
                Object value = metadata.getFieldValue(entity, field);
                stmt.setObject(paramIndex++, value);
            }
            
            // Bind ID value (for WHERE clause)
            Object idValue = metadata.getIdValue(entity);
            stmt.setObject(paramIndex, idValue);
            
            // Execute UPDATE
            int rowsAffected = stmt.executeUpdate();
            
            if (rowsAffected == 0) {
                throw new RuntimeException("No rows updated. Entity may not exist: " + idValue);
            }
            
            // Fire post-update interceptors
            InterceptorRegistry.getInstance().firePostUpdate(entity);
            
            return entity;
            
        } catch (SQLException e) {
            throw new RuntimeException("Failed to update entity: " + entity.getClass().getName(), e);
        }
    }
    
    @Override
    public <T> void delete(T entity) {
        checkClosed();
        
        // Fire pre-delete interceptors
        if (!InterceptorRegistry.getInstance().firePreDelete(entity)) {
            return; // Operation cancelled by interceptor
        }
        
        EntityMetadata metadata = MetadataParser.parse(entity.getClass());
        String sql = SQLGenerator.generateDeleteSQL(metadata);
        
        try (PreparedStatement stmt = connection.prepareStatement(sql)) {
            // Bind ID value
            Object idValue = metadata.getIdValue(entity);
            stmt.setObject(1, idValue);
            
            // Execute DELETE
            int rowsAffected = stmt.executeUpdate();
            
            if (rowsAffected == 0) {
                throw new RuntimeException("No rows deleted. Entity may not exist: " + idValue);
            }
            
            // Fire post-delete interceptors
            InterceptorRegistry.getInstance().firePostDelete(entity);
            
        } catch (SQLException e) {
            throw new RuntimeException("Failed to delete entity: " + entity.getClass().getName(), e);
        }
    }
    
    @Override
    public <T> T find(Class<T> entityClass, Object id) {
        checkClosed();
        
        EntityMetadata metadata = MetadataParser.parse(entityClass);
        String sql = SQLGenerator.generateSelectByIdSQL(metadata);
        
        try (PreparedStatement stmt = connection.prepareStatement(sql)) {
            stmt.setObject(1, id);
            
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    T entity = ResultSetMapper.mapRow(rs, metadata);
                    
                    // Fire post-load interceptors
                    InterceptorRegistry.getInstance().firePostLoad(entity);
                    
                    return entity;
                }
                return null; // Not found
            }
            
        } catch (SQLException e) {
            throw new RuntimeException("Failed to find entity: " + entityClass.getName() + " with id: " + id, e);
        }
    }
    
    @Override
    public <T> QueryBuilder<T> createQuery(Class<T> entityClass) {
        checkClosed();
        return new QueryBuilder<>(entityClass, this);
    }
    
    @Override
    public Transaction beginTransaction() {
        checkClosed();
        if (currentTransaction != null && currentTransaction.isActive()) {
            throw new IllegalStateException("A transaction is already active");
        }
        currentTransaction = new TransactionImpl(connection);
        currentTransaction.begin();
        return currentTransaction;
    }
    
    @Override
    public Transaction getTransaction() {
        return currentTransaction;
    }
    
    @Override
    public void close() {
        if (!closed) {
            try {
                // Rollback any active transaction
                if (currentTransaction != null && currentTransaction.isActive()) {
                    currentTransaction.rollback();
                }
                connection.close();
            } catch (SQLException e) {
                throw new RuntimeException("Failed to close session", e);
            } finally {
                closed = true;
            }
        }
    }
    
    /**
     * Execute a query and return results.
     * Used internally by QueryBuilder.
     */
    public <T> List<T> executeQuery(String sql, List<Object> parameters, Class<T> entityClass) {
        checkClosed();
        
        EntityMetadata metadata = MetadataParser.parse(entityClass);
        
        try (PreparedStatement stmt = connection.prepareStatement(sql)) {
            // Bind parameters
            for (int i = 0; i < parameters.size(); i++) {
                stmt.setObject(i + 1, parameters.get(i));
            }
            
            try (ResultSet rs = stmt.executeQuery()) {
                return ResultSetMapper.mapRows(rs, metadata);
            }
            
        } catch (SQLException e) {
            throw new RuntimeException("Failed to execute query: " + sql, e);
        }
    }
    
    /**
     * Execute a count query.
     */
    public long executeCount(String sql, List<Object> parameters) {
        checkClosed();
        
        try (PreparedStatement stmt = connection.prepareStatement(sql)) {
            for (int i = 0; i < parameters.size(); i++) {
                stmt.setObject(i + 1, parameters.get(i));
            }
            
            try (ResultSet rs = stmt.executeQuery()) {
                return ResultSetMapper.mapLongValue(rs);
            }
            
        } catch (SQLException e) {
            throw new RuntimeException("Failed to execute count query: " + sql, e);
        }
    }
    
    /**
     * Get the underlying JDBC connection.
     * Use with caution for advanced operations.
     */
    public Connection getConnection() {
        return connection;
    }
    
    /**
     * Get the current dialect.
     */
    public Dialect getDialect() {
        return dialect;
    }
    
    /**
     * Check if session is closed.
     */
    private void checkClosed() {
        if (closed) {
            throw new IllegalStateException("Session is closed");
        }
    }
    
    /**
     * Convert generated ID to the target type.
     */
    private Object convertIdType(Object value, Class<?> targetType) {
        if (value == null) return null;
        
        if (targetType == Long.class || targetType == long.class) {
            return ((Number) value).longValue();
        }
        if (targetType == Integer.class || targetType == int.class) {
            return ((Number) value).intValue();
        }
        
        return value;
    }
}
