package com.dam.framework.dialect;

import com.dam.framework.engine.EntityMetadata;
import com.dam.framework.engine.SQLGenerator;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Date;

/**
 * H2 Database Dialect - In-memory database for testing.
 * No installation required - perfect for demos and testing.
 * 
 * Design Pattern: Strategy Pattern (GoF Pattern #2)
 * 
 * @author Dev 1 & Dev 2
 */
public class H2Dialect implements Dialect {
    
    @Override
    public String getInsertSQL(EntityMetadata metadata) {
        return SQLGenerator.generateInsertSQL(metadata);
    }
    
    @Override
    public String getUpdateSQL(EntityMetadata metadata) {
        return SQLGenerator.generateUpdateSQL(metadata);
    }
    
    @Override
    public String getDeleteSQL(EntityMetadata metadata) {
        return SQLGenerator.generateDeleteSQL(metadata);
    }
    
    @Override
    public String getSelectSQL(EntityMetadata metadata) {
        return SQLGenerator.generateSelectSQL(metadata);
    }
    
    @Override
    public String getSelectByIdSQL(EntityMetadata metadata) {
        return SQLGenerator.generateSelectByIdSQL(metadata);
    }
    
    @Override
    public String getPaginationSQL(String sql, int limit, int offset) {
        // H2 uses same syntax as MySQL/PostgreSQL
        return sql + " LIMIT " + limit + " OFFSET " + offset;
    }
    
    @Override
    public String getColumnType(Class<?> javaType) {
        // Map Java types to H2 column types
        if (javaType == String.class) return "VARCHAR(255)";
        if (javaType == Integer.class || javaType == int.class) return "INT";
        if (javaType == Long.class || javaType == long.class) return "BIGINT";
        if (javaType == Double.class || javaType == double.class) return "DOUBLE";
        if (javaType == Float.class || javaType == float.class) return "FLOAT";
        if (javaType == Boolean.class || javaType == boolean.class) return "BOOLEAN";
        if (javaType == Short.class || javaType == short.class) return "SMALLINT";
        if (javaType == Byte.class || javaType == byte.class) return "TINYINT";
        if (javaType == BigDecimal.class) return "DECIMAL(19,4)";
        if (javaType == Date.class) return "DATE";
        if (javaType == Timestamp.class) return "TIMESTAMP";
        if (javaType == LocalDate.class) return "DATE";
        if (javaType == LocalDateTime.class) return "TIMESTAMP";
        if (javaType == byte[].class) return "BLOB";
        
        return "VARCHAR(255)"; // default
    }
    
    @Override
    public String getIdentityColumnString() {
        return "AUTO_INCREMENT";
    }
    
    /**
     * Get H2-specific CREATE TABLE syntax.
     */
    public String getCreateTableSQL(EntityMetadata metadata) {
        StringBuilder sql = new StringBuilder("CREATE TABLE IF NOT EXISTS ");
        sql.append(metadata.getTableName()).append(" (");
        
        // Add columns
        boolean first = true;
        for (var field : metadata.getFields()) {
            if (!first) sql.append(", ");
            first = false;
            
            sql.append(metadata.getColumnName(field)).append(" ");
            sql.append(getColumnType(field.getType()));
            
            // Add PRIMARY KEY and AUTO_INCREMENT for ID field
            if (field.equals(metadata.getIdField())) {
                sql.append(" PRIMARY KEY");
                if (metadata.isIdAutoGenerated()) {
                    sql.append(" ").append(getIdentityColumnString());
                }
            }
        }
        
        sql.append(")");
        return sql.toString();
    }
}
