package com.dam.framework.dialect;

import com.dam.framework.engine.EntityMetadata;
import com.dam.framework.engine.SQLGenerator;

import java.lang.reflect.Field;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.Date;

/**
 * PostgreSQL-specific SQL dialect implementation.
 * Supports PostgreSQL 9.5+ features including RETURNING clause.
 * 
 * @author Dev 1
 */
public class PostgreSQLDialect implements Dialect {
    
    private final SQLGenerator sqlGenerator = new SQLGenerator();
    
    @Override
    public String getInsertSQL(EntityMetadata metadata) {
        // Use standard INSERT with RETURNING for PostgreSQL
        String baseInsert = sqlGenerator.generateInsertSQL(metadata);
        // Add RETURNING clause for auto-generated ID
        if (metadata.isIdAutoGenerated()) {
            return baseInsert.replace(";", "") + " RETURNING " + metadata.getIdColumnName();
        }
        return baseInsert;
    }
    
    @Override
    public String getUpdateSQL(EntityMetadata metadata) {
        return sqlGenerator.generateUpdateSQL(metadata);
    }
    
    @Override
    public String getDeleteSQL(EntityMetadata metadata) {
        return sqlGenerator.generateDeleteSQL(metadata);
    }
    
    @Override
    public String getSelectSQL(EntityMetadata metadata) {
        return sqlGenerator.generateSelectSQL(metadata);
    }
    
    @Override
    public String getSelectByIdSQL(EntityMetadata metadata) {
        return sqlGenerator.generateSelectByIdSQL(metadata);
    }
    
    @Override
    public String getPaginationSQL(String sql, int limit, int offset) {
        // PostgreSQL uses: LIMIT ? OFFSET ?
        StringBuilder sb = new StringBuilder(sql);
        if (limit > 0) {
            sb.append(" LIMIT ").append(limit);
        }
        if (offset > 0) {
            sb.append(" OFFSET ").append(offset);
        }
        return sb.toString();
    }
    
    @Override
    public String getColumnType(Class<?> javaType) {
        // Map Java types to PostgreSQL column types
        if (javaType == String.class) return "VARCHAR(255)";
        if (javaType == Integer.class || javaType == int.class) return "INTEGER";
        if (javaType == Long.class || javaType == long.class) return "BIGINT";
        if (javaType == Short.class || javaType == short.class) return "SMALLINT";
        if (javaType == Byte.class || javaType == byte.class) return "SMALLINT";
        if (javaType == Float.class || javaType == float.class) return "REAL";
        if (javaType == Double.class || javaType == double.class) return "DOUBLE PRECISION";
        if (javaType == Boolean.class || javaType == boolean.class) return "BOOLEAN";
        if (javaType == BigDecimal.class) return "NUMERIC(19,4)";
        if (javaType == BigInteger.class) return "NUMERIC(19,0)";
        if (javaType == Date.class || javaType == LocalDateTime.class) return "TIMESTAMP";
        if (javaType == LocalDate.class) return "DATE";
        if (javaType == LocalTime.class) return "TIME";
        if (javaType == byte[].class) return "BYTEA";
        if (javaType == Character.class || javaType == char.class) return "CHAR(1)";
        return "VARCHAR(255)";
    }
    
    @Override
    public String getIdentityColumnString() {
        return "SERIAL"; // PostgreSQL uses SERIAL/BIGSERIAL for auto-increment
    }
    
    /**
     * Get CREATE TABLE SQL for PostgreSQL.
     * 
     * @param metadata Entity metadata
     * @return CREATE TABLE SQL statement
     */
    public String getCreateTableSQL(EntityMetadata metadata) {
        StringBuilder sql = new StringBuilder();
        sql.append("CREATE TABLE IF NOT EXISTS ");
        sql.append(metadata.getTableName());
        sql.append(" (");
        
        boolean first = true;
        
        // ID field first
        Field idField = metadata.getIdField();
        if (idField != null) {
            String idColumnName = metadata.getIdColumnName();
            if (metadata.isIdAutoGenerated()) {
                // Use BIGSERIAL for auto-generated Long IDs
                sql.append(idColumnName).append(" BIGSERIAL PRIMARY KEY");
            } else {
                sql.append(idColumnName).append(" ")
                   .append(getColumnType(idField.getType()))
                   .append(" PRIMARY KEY");
            }
            first = false;
        }
        
        // Other fields
        for (Field field : metadata.getNonIdFields()) {
            if (!first) {
                sql.append(", ");
            }
            String columnName = metadata.getColumnName(field);
            sql.append(columnName).append(" ").append(getColumnType(field.getType()));
            first = false;
        }
        
        sql.append(")");
        return sql.toString();
    }
    
    /**
     * Get the PostgreSQL driver class name.
     * 
     * @return Driver class name
     */
    public String getDriverClassName() {
        return "org.postgresql.Driver";
    }
    
    /**
     * Check if a feature is supported.
     * 
     * @param feature Feature name
     * @return true if supported
     */
    public boolean supportsFeature(String feature) {
        switch (feature.toUpperCase()) {
            case "RETURNING":
            case "UPSERT":
            case "ARRAY":
            case "JSON":
            case "JSONB":
            case "CTE":
            case "WINDOW_FUNCTIONS":
                return true;
            default:
                return false;
        }
    }
}
