# Thông tin kết nối CSDL mẫu
db.url=jdbc:mysql://localhost:3306/demo_db
db.username=root
db.password=yourpassword
# Cấu hình Dialect cho Strategy Pattern
db.dialect=com.dam.framework.dialect.MySQLDialect
# Cấu hình Connection Pool
db.pool.max_size=10